repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.12.2
    hooks:
      - id: ansible-lint
        files: ^playbooks/.*\.(yaml|yml)$
        additional_dependencies:
          - ansible-core==2.18.18
